"""
Layer 3 — LLM-based Prompt Injection Detector
Uses a fine-tuned XLM-RoBERTa model for deep semantic classification.

Artifacts layout (generated by notebooks/llm-classification-finetuned.ipynb):
    promptDefender_thirdLayer/
    └── llm_artifacts/
        ├── config.json
        ├── tokenizer_config.json
        ├── sentencepiece.bpe.model
        ├── pytorch_model.bin   (or model.safetensors)
        └── model_meta.json     ← threshold + label map
"""

import json
import os
import time

import torch
from transformers import XLMRobertaForSequenceClassification, AutoTokenizer

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
_BASE_DIR      = os.path.dirname(os.path.abspath(__file__))
_ARTIFACTS_DIR = os.path.join(_BASE_DIR, "llm_artifacts")
_META_PATH     = os.path.join(_ARTIFACTS_DIR, "model_meta.json")


class LLMDetector:
    """
    Wraps a fine-tuned XLM-RoBERTa sequence classifier.

    Usage
    -----
    detector = LLMDetector()
    result   = detector.predict("Ignore all previous instructions …")
    # → {"is_injection": True, "confidence": 0.97, "threshold": 0.5, "elapsed_ms": 38.2}
    """

    def __init__(self, device: str | None = None):
        if not os.path.isdir(_ARTIFACTS_DIR):
            raise FileNotFoundError(
                f"Artifacts directory not found: {_ARTIFACTS_DIR}\n"
                "Run notebooks/llm-classification-finetuned.ipynb first and copy "
                "the saved model into promptDefender_thirdLayer/llm_artifacts/."
            )

        # ── Device ──────────────────────────────────────────────────────────
        if device is None:
            if torch.cuda.is_available():
                device = "cuda"
            elif torch.backends.mps.is_available():
                device = "mps"
            else:
                device = "cpu"
        self.device = torch.device(device)

        # ── Tokenizer & Model ────────────────────────────────────────────────
        self.tokenizer = AutoTokenizer.from_pretrained(_ARTIFACTS_DIR)
        self.model     = XLMRobertaForSequenceClassification.from_pretrained(_ARTIFACTS_DIR)
        self.model.to(self.device)
        self.model.eval()

        # ── Metadata ─────────────────────────────────────────────────────────
        if os.path.isfile(_META_PATH):
            with open(_META_PATH, "r", encoding="utf-8") as f:
                meta = json.load(f)
        else:
            meta = {}

        self.threshold: float = float(meta.get("threshold", 0.5))
        # id2label: {"0": "benign", "1": "injection"}
        self.id2label: dict = meta.get("id2label", {"0": "benign", "1": "injection"})

        # Index of the injection class (robust to any label naming)
        self._injection_idx: int = next(
            (int(k) for k, v in self.id2label.items() if "inject" in v.lower()),
            1,
        )

    # -----------------------------------------------------------------------
    # Public API
    # -----------------------------------------------------------------------

    def predict(self, prompt: str) -> dict:
        """
        Classify a single prompt.

        Returns
        -------
        dict
            is_injection : bool
            confidence   : float   probability of the injection class
            threshold    : float   decision boundary used
            elapsed_ms   : float
        """
        t0 = time.perf_counter()

        inputs = self.tokenizer(
            prompt,
            return_tensors="pt",
            truncation=True,
            max_length=512,
            padding=True,
        ).to(self.device)

        with torch.no_grad():
            logits = self.model(**inputs).logits          # (1, num_labels)
            probs  = torch.softmax(logits, dim=-1)[0]     # (num_labels,)

        confidence   = float(probs[self._injection_idx].item())
        is_injection = confidence >= self.threshold
        elapsed_ms   = (time.perf_counter() - t0) * 1_000

        return {
            "is_injection": is_injection,
            "confidence":   round(confidence, 4),
            "threshold":    self.threshold,
            "elapsed_ms":   round(elapsed_ms, 2),
        }

    def predict_batch(self, prompts: list[str], batch_size: int = 16) -> list[dict]:
        """
        Classify a list of prompts efficiently in mini-batches.
        elapsed_ms is None per sample (not meaningful in batch mode).
        """
        results = []
        for i in range(0, len(prompts), batch_size):
            batch  = prompts[i : i + batch_size]
            inputs = self.tokenizer(
                batch,
                return_tensors="pt",
                truncation=True,
                max_length=512,
                padding=True,
            ).to(self.device)

            with torch.no_grad():
                logits = self.model(**inputs).logits
                probs  = torch.softmax(logits, dim=-1)

            for prob_row in probs:
                conf = float(prob_row[self._injection_idx].item())
                results.append({
                    "is_injection": conf >= self.threshold,
                    "confidence":   round(conf, 4),
                    "threshold":    self.threshold,
                    "elapsed_ms":   None,
                })
        return results
